cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "neovim/neovim"
brew "automake"
brew "coreutils"
brew "gnupg"
brew "gpg-agent"
brew "jq"
brew "libtool"
brew "readline"
brew "libxslt"
brew "libyaml"
brew "neovim"
brew "unixodbc"
brew "wget"
